all:
  exclude:
    - 'spec/**/*'
github:
  slug: raymonschouwenaar/raymonschouwenaar-blog
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
github_pr:
  format: "%{runner} - %{msg}"
max_warnings: 150
verbose: false
