baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Raymon Schouwenaar"
description = "Blog about HTML, CSS, JavaScript and Frontend Tools"
author = "Raymon Schouwenaar"
githubName = "rsschouwenaar"
twitterName = "rsschouwenaar"

theme = "blank"
DisqusShortname = "raymonschouwenaar"

googleAnalytics = "UA-37807942-1"

[twitter]
    card = "summary_large_image"
    site = "@rsschouwenaar"
    creator = "@rsschouwenaar"
    title = "Special Title for the Card"
    description = "Special Description for the card max. 200 characters"
    image = "https://example.com/great-picture.jpg"

contentdir = "content"
publishdir = "dist"

[permalinks]
post = "/:title/"
page = "/:slug/"
category = "category/:slug"

[[menu.main]]
    name = "About Raymon"
    pre = "<i class='fa fa-heart'></i>"
    weight = -90
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/"