baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Raymon Schouwenaar"
theme = "blank"
DisqusShortname = "raymonschouwenaar"

googleAnalytics = "UA-37807942-1"


contentdir = "content"
publishdir = "dist"

[params]
author = "Raymon Schouwenaar"
githubName = "rsschouwenaar"
twitterName = "rsschouwenaar"
description = "I'm Ray a Dutch Front-end Developer. I share my passion about HTML, CSS, JavaScript and Tooling!"

[permalinks]
post = "/:title/"
page = "/:slug/"
category = "category/:slug"

[[menu.main]]
    name = "About Raymon"
    pre = "<i class='fa fa-heart'></i>"
    weight = -90
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/"
[[menu.main]]
    name = "Developer Webhosting"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    url = "https://www.webfaction.com/?aid=73781"