baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Raymon Schouwenaar.nl"
relativeURLs = true
theme = "blank"
DisqusShortname = "raymonschouwenaar"

[permalinks]
post = "/:year/:month/:title/"
page = "/:slug/"