baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "RAYs{FRONTEND}BYTES"
theme = "blank"
DisqusShortname = "raymonschouwenaar"

googleAnalytics = "UA-37807942-1"

pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=table"

contentdir = "content"
publishdir = "dist"

[blackfriday]
hrefTargetBlank = true

[params]
author = "Raymon Schouwenaar"
githubName = "rsschouwenaar"
twitterName = "rsschouwenaar"
description = "I'm Ray a Dutch Front-end Developer. I share my passion about HTML, CSS, JavaScript and Tooling!"
UseChroma = true

[permalinks]
post = "/:title/"
page = "/:slug/"
category = "category/:slug"

[[menu.main]]
    name = "About Raymon"
    pre = "<i class='fa fa-heart'></i>"
    weight = -90
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/"
[[menu.main]]
    name = "Developer Webhosting"
    pre = "<i class='fa fa-road'></i>"
    weight = -80
    url = "https://www.webfaction.com/?aid=73781"